# Generated by Django 4.2.7 on 2023-11-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='img',
            field=models.ImageField(default='media/image.jpg', upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
