# Generated by Django 4.2.7 on 2023-11-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_destination_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(default='media/image.jpg', upload_to='img'),
        ),
    ]
